### ISSUE TITLE
'core.adminlte.middleware.ApiPermissionCheck',普通用户检测是否正常.时会直接抛错

### ISSUE THREAD

**Issue by ghost** [lyhapple/django-adminlte#23]
core.adminlte.middleware.ApiPermissionCheck
代码中.21行
原始写法
for p in permissions:
    resources.append(p.resources.values_list('url', flat=True))  
此写法.会导致普通.权限用户.直接返回403
修改后 正常.
resources.append(list(p.resources.values_list('url', flat=True)))

**Comment by ghost** [comment]
另.非常想加入您的这个代码开发中...

**Comment by lyhapple** [comment]
感谢提交issue,  你可以直接fork代码，提交PR，然后我来合并，这样你就其实已经加入到代码开发中了，我目前还没有特别好的产品想法(没有需求，没有方向)，所以推进的很慢，欢迎提交新模块，或改进原有代码

**Comment by ghost** [comment]
第二个问题...刚刚忘记说了.
同行代码中.发现取出的是一个list包含list的方法.url 默认是url 是字符串.不能进行 not in 操作.... 稍微改了下.
for List in resources:
                if type(List) != list:
                    if str(request.path_info) != str(List):
                        return HttpResponse(status=403)
                else:
                    if request.path_info not in List:
                        return HttpResponse(status=403)

**Comment by ghost** [comment]
好的.稍后.我回直接fork 一份代码.有更改的需求.我会直接在里面说明.

**Comment by ghost** [comment]
我目前还正在看您的.代码......准备是拿到生产上做发布管理系统.以及流程系统

**Comment by lyhapple** [comment]
感谢感谢  :)
