### ISSUE TITLE
apps 明会导致歧义

### ISSUE THREAD

**Issue by ghost** [lyhapple/django-adminlte#25]
今天在创建一个任务的时候.apps会导致出现报错.
修改apps为mapps后正常.
建议apps改成其他的名称.

**Comment by lyhapple** [comment]
是的, 我最近也发现了, 后面准备换一个

**Comment by ghost** [comment]
换成{mapps}吧
这个肯定不重复....

**Comment by lyhapple** [comment]
感谢提醒, 已经修改了.
