### ISSUE TITLE
ImportError: No module named 'serializers'

### ISSUE THREAD

**Issue by xianfuxing** [lyhapple/django-adminlte#27]
ImportError: No module named 'serializers'
你好，我安装requirement.txt安装依赖包，不过报错。

**Comment by lyhapple** [comment]
你是第一个提出安装失败的， 先看看你的环境里是否已经成功安装django-rest-framework库， 还不行的话，请把详细信息贴出来， 按照readme里的方法做，是不太可能出错的。

**Comment by xianfuxing** [comment]
> Traceback (most recent call last):
>   File "manage_dev.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "d:\Desktop\venv\lib\site-packages\django\core\management__init__.py", line 338, in execute_from_command_line
>     utility.execute()
>   File "d:\Desktop\venv\lib\site-packages\django\core\management__init__.py", line 312, in execute
>     django.setup()
>   File "d:\Desktop\venv\lib\site-packages\django__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "d:\Desktop\venv\lib\site-packages\django\apps\registry.py", line 115, in populate
>     app_config.ready()
>   File "d:\Desktop\django-adminlte\core\adminlte\apps.py", line 12, in ready
>     import serializers
> ImportError: No module named 'serializers'

django-rest-framework 是确定安装了。

**Comment by xianfuxing** [comment]
另外，我补充下：
执行
`python manage_dev.py migrate`
的时候提示：

>   File "d:\Desktop\django-adminlte\lteadmin\settings_dev.py", line 3, in <module>
>     from settings import *
> ImportError: No module named 'settings'

我就修改了下：
from settings import \* -> from .settings import *

我想这个应该是没有影响的。

**Comment by lyhapple** [comment]
正常情况下是不需要改动任何代码的， 应该要看看你是不是进入了虚拟命令行环境， 就是CMD前面会有个括号，用来标识当前的虚拟环境名称， 引入virtualenv这个库，就是为了做好隔离，不与本机实际库产生关系。 

重点是执行 source lte/bin/activate 命令，这样就可以进入虚拟环境， 这是在osx或linux平台用的。

如果是windows系统， 好像是要先进入let/bin目录 ,然后执行 activate.bat

总之，确保进入虚拟环境， 然后在虚拟环境中pip install -r requirements.txt

另外，如果你用了pycharm 这类的IDE打开了这个项目， 请确保你的python执行环境配置正确，应该指向virtualenv创建的那个python环境
